print("Hello World")
#Print the output ....
print(200+300)
#Print Exactly the same
print('200+300')

#Print two statements at a time ...
# Print multiple values at a time using commas...
print("Hi","My name is Shekhar ...","Im am a Louisiana Tech Student...")

#U can even print conditional statements using print function...
print(5>3)
